---
#open firewall ports and restart firewalld
- name: open http port
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: open https port
  firewalld:
    service: https
    state: enabled
  notify:
  - restart firewalld service

- name: Disable selinux
  selinux:
    policy: targeted
    state: disabled