---
#start mysql service, create admin user, create nextcloud database and delete remote user
- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started

- name: set root password mariadb
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost

- name: Create Database user admin
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: nextcloud_user
    password: "{{ mysql_admin_password }}"
    priv: '*.*:ALL'
    state: present

- name: create wordpress Database
  mysql_db:
    login_user: nextcloud_user
    login_password: "{{ mysql_admin_password }}"
    name: nextcloud_db
    state: present

#- name: delete remote root
#  mysql_user:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    user: root
#    check_implicit_admin: true
#    host: "{{ ansible_fqdn }}"
#    state: absent